"""offre prix_heure (taux horaire)

Revision ID: 29141829c688
Revises: 343c273b35c3
Create Date: 2026-06-11 18:42:01.416825
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29141829c688'
down_revision: Union[str, None] = '343c273b35c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('offres', sa.Column('prix_heure', sa.Numeric(precision=8, scale=4), server_default='27', nullable=False))
    # Backfill : taux horaire = tarif_achat / heures pour PRESERVER les tarifs
    # d'achat existants (les tarifs ronds historiques ont des taux non entiers).
    op.execute(
        "UPDATE offres SET prix_heure = ROUND(tarif_achat / heures, 4) WHERE heures > 0"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offres', 'prix_heure')
    # ### end Alembic commands ###
