"""ajout total_offerts_recurrent_ht au devis

Revision ID: 2d30cbf3e4b7
Revises: 
Create Date: 2026-05-29 22:23:49.512893
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d30cbf3e4b7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('total_offerts_recurrent_ht', sa.Numeric(precision=10, scale=2), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devis', 'total_offerts_recurrent_ht')
    # ### end Alembic commands ###
