"""client_tva_intracom snapshot devis

Revision ID: 74c54aff7c28
Revises: f2a3b4c5d6e7
Create Date: 2026-06-11 12:26:10.331708
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c54aff7c28'
down_revision: Union[str, None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devis', sa.Column('client_tva_intracom', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devis', 'client_tva_intracom')
    # ### end Alembic commands ###
